# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PortfolioPosition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, wkn: str=None, amount: int=None, stock_name: str=None, country_id: str=None, logo_url: str=None):  # noqa: E501
        """PortfolioPosition - a model defined in Swagger

        :param wkn: The wkn of this PortfolioPosition.  # noqa: E501
        :type wkn: str
        :param amount: The amount of this PortfolioPosition.  # noqa: E501
        :type amount: int
        :param stock_name: The stock_name of this PortfolioPosition.  # noqa: E501
        :type stock_name: str
        :param country_id: The country_id of this PortfolioPosition.  # noqa: E501
        :type country_id: str
        :param logo_url: The logo_url of this PortfolioPosition.  # noqa: E501
        :type logo_url: str
        """
        self.swagger_types = {
            'wkn': str,
            'amount': int,
            'stock_name': str,
            'country_id': str,
            'logo_url': str
        }

        self.attribute_map = {
            'wkn': 'wkn',
            'amount': 'amount',
            'stock_name': 'stockName',
            'country_id': 'countryId',
            'logo_url': 'logoUrl'
        }

        self._wkn = wkn
        self._amount = amount
        self._stock_name = stock_name
        self._country_id = country_id
        self._logo_url = logo_url

    @classmethod
    def from_dict(cls, dikt) -> 'PortfolioPosition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PortfolioPosition of this PortfolioPosition.  # noqa: E501
        :rtype: PortfolioPosition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wkn(self) -> str:
        """Gets the wkn of this PortfolioPosition.


        :return: The wkn of this PortfolioPosition.
        :rtype: str
        """
        return self._wkn

    @wkn.setter
    def wkn(self, wkn: str):
        """Sets the wkn of this PortfolioPosition.


        :param wkn: The wkn of this PortfolioPosition.
        :type wkn: str
        """

        self._wkn = wkn

    @property
    def amount(self) -> int:
        """Gets the amount of this PortfolioPosition.


        :return: The amount of this PortfolioPosition.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this PortfolioPosition.


        :param amount: The amount of this PortfolioPosition.
        :type amount: int
        """

        self._amount = amount

    @property
    def stock_name(self) -> str:
        """Gets the stock_name of this PortfolioPosition.


        :return: The stock_name of this PortfolioPosition.
        :rtype: str
        """
        return self._stock_name

    @stock_name.setter
    def stock_name(self, stock_name: str):
        """Sets the stock_name of this PortfolioPosition.


        :param stock_name: The stock_name of this PortfolioPosition.
        :type stock_name: str
        """

        self._stock_name = stock_name

    @property
    def country_id(self) -> str:
        """Gets the country_id of this PortfolioPosition.


        :return: The country_id of this PortfolioPosition.
        :rtype: str
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id: str):
        """Sets the country_id of this PortfolioPosition.


        :param country_id: The country_id of this PortfolioPosition.
        :type country_id: str
        """

        self._country_id = country_id

    @property
    def logo_url(self) -> str:
        """Gets the logo_url of this PortfolioPosition.


        :return: The logo_url of this PortfolioPosition.
        :rtype: str
        """
        return self._logo_url

    @logo_url.setter
    def logo_url(self, logo_url: str):
        """Sets the logo_url of this PortfolioPosition.


        :param logo_url: The logo_url of this PortfolioPosition.
        :type logo_url: str
        """

        self._logo_url = logo_url
