---
swagger: "2.0"
info:
  description: "Absolute legendary PyBroker BackEnd API"
  version: "1.0.0"
  title: "PyBroker"
host: "localhost:8080"
basePath: "/api"
tags:
- name: "portfolio"
  description: "Contains operations about a users portfolio"
- name: "stock"
  description: "Contains stock information"
- name: "user"
  description: "Contains operations about user"
schemes:
- "https"
- "http"
paths:
  /portfolio:
    get:
      tags:
      - "portfolio"
      summary: "Get all current positions"
      description: "Returns all the current stock positions of the logged in user"
      operationId: "get_portfolio"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PortfolioPosition"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.portfolio_controller"
  /portfolio/value:
    get:
      tags:
      - "portfolio"
      summary: "Get the performance of the portfolio"
      description: "Returns the logged in users portfolio performance"
      operationId: "get_portfolio_value"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PortfolioValue"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.portfolio_controller"
  /portfolio/transaction:
    post:
      tags:
      - "portfolio"
      summary: "Create a new stock transaction"
      description: "Creates and executes a transaction for the logged in user"
      operationId: "create_transaction"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "transaction_prepare_param"
        description: "The transaction to create."
        required: true
        schema:
          $ref: "#/definitions/TransactionPrepare"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Transaction"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.portfolio_controller"
  /stock:
    get:
      tags:
      - "stock"
      summary: "Get all stocks in database"
      description: "Returns all available stocks from the database"
      operationId: "get_stocks"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/StockSearchResult"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.stock_controller"
  /stock/{symbol}/history:
    get:
      tags:
      - "stock"
      summary: "Get historical data of given stock"
      description: "Returns all available stocks from the database"
      operationId: "get_stock_history"
      produces:
      - "application/json"
      parameters:
      - name: "symbol"
        in: "path"
        description: "Symbol of searched stock"
        required: true
        type: "string"
      - name: "period"
        in: "query"
        description: "Period of stock data"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/StockValue"
        "404":
          description: "data for stock and period not found"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.stock_controller"
  /stock/{symbol}/description:
    get:
      tags:
      - "stock"
      summary: "Get financials of given stock"
      description: ""
      operationId: "get_stock_description"
      produces:
      - "application/json"
      parameters:
      - name: "symbol"
        in: "path"
        description: "Symbol of searched stock"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/StockDescription"
        "404":
          description: "data for stock and period not found"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.stock_controller"
  /user:
    get:
      tags:
      - "user"
      summary: "Get user from api_key"
      description: "This can only be done by the logged in user and will return a\
        \ user object"
      operationId: "get_user"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "The response"
          schema:
            $ref: "#/definitions/User"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "create_user"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user_param"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/login:
    post:
      tags:
      - "user"
      summary: "Logs user into the system and returns auth key"
      description: ""
      operationId: "login_user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user_prepare_login_param"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/UserPrepareLogin"
      responses:
        "200":
          description: "The response"
          schema:
            $ref: "#/definitions/AuthKey"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logout_user"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/{user_id}:
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "delete_user"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/settings:
    get:
      tags:
      - "user"
      summary: "Get the settings of the logged in user"
      description: "Returns the settings of the logged in user"
      operationId: "get_user_settings"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Settings"
        "404":
          description: "No settings for the logged in user"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    post:
      tags:
      - "user"
      summary: "Create/set settings for logged in user"
      description: "Create/set the broker settings for the logged in user"
      operationId: "create_user_settings"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "settings_param"
        description: "Created settings object"
        required: true
        schema:
          $ref: "#/definitions/Settings"
      responses:
        default:
          description: "successful operation"
      security:
      - api_key: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
    x-apikeyInfoFunc: "swagger_server.services.auth_service.api_key_auth"
definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      userId:
        type: "integer"
        format: "int64"
      symbol:
        type: "string"
      stockValueId:
        type: "integer"
        format: "int64"
      amount:
        type: "integer"
        format: "int32"
      transactionType:
        type: "string"
        enum:
        - "buy"
        - "sell"
      transactionFee:
        type: "number"
        format: "float"
    example:
      transactionType: "buy"
      symbol: "symbol"
      amount: 5
      transactionFee: 5.637377
      stockValueId: 1
      id: 0
      userId: 6
  TransactionPrepare:
    type: "object"
    properties:
      symbol:
        type: "string"
      amount:
        type: "integer"
        format: "int32"
      transactionType:
        type: "string"
        enum:
        - "buy"
        - "sell"
  StockSearchResult:
    type: "object"
    properties:
      symbol:
        type: "string"
      stockName:
        type: "string"
    example:
      symbol: "symbol"
      stockName: "stockName"
  StockValue:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      symbol:
        type: "string"
      stock_price:
        type: "number"
        format: "float"
      timestamp:
        type: "string"
        format: "date-time"
    example:
      symbol: "symbol"
      stock_price: 6.0274563
      id: 0
      timestamp: "2000-01-23T04:56:07.000+00:00"
  StockDescription:
    type: "object"
    properties:
      symbol:
        type: "string"
      stockName:
        type: "string"
      countryId:
        type: "string"
      logoUrl:
        type: "string"
        format: "uri"
      longDescription:
        type: "string"
      industry:
        type: "string"
      dividend:
        type: "string"
      infoLoaded:
        type: "boolean"
      historyLoaded:
        type: "boolean"
    example:
      longDescription: "longDescription"
      historyLoaded: true
      symbol: "symbol"
      stockName: "stockName"
      dividend: "dividend"
      industry: "industry"
      countryId: "countryId"
      logoUrl: "http://example.com/aeiou"
      infoLoaded: true
  PortfolioPosition:
    type: "object"
    properties:
      symbol:
        type: "string"
      logoUrl:
        type: "string"
        format: "uri"
      stockName:
        type: "string"
      amount:
        type: "integer"
        format: "int32"
      stock_price:
        type: "number"
        format: "float"
      stock_buyin_price:
        type: "number"
        format: "float"
      countryId:
        type: "string"
      industry:
        type: "string"
    example:
      symbol: "symbol"
      amount: 0
      stockName: "stockName"
      stock_buyin_price: 1.4658129
      stock_price: 6.0274563
      industry: "industry"
      logoUrl: "http://example.com/aeiou"
      countryId: "countryId"
  PortfolioValue:
    type: "object"
    properties:
      marketValue:
        type: "number"
        format: "float"
      timestamp:
        type: "string"
        format: "date-time"
    example:
      marketValue: 0.8008282
      timestamp: "2000-01-23T04:56:07.000+00:00"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      startingCapital:
        type: "number"
        format: "float"
      moneyAvailable:
        type: "number"
        format: "float"
    example:
      firstName: "firstName"
      lastName: "lastName"
      moneyAvailable: 1.4658129
      password: "password"
      id: 0
      startingCapital: 6.0274563
      email: "email"
  UserPrepareLogin:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
    example:
      password: "password"
      email: "email"
  Settings:
    type: "object"
    properties:
      transactionFee:
        type: "number"
        format: "float"
    example:
      transactionFee: 0.8008282
  AuthKey:
    type: "object"
    properties:
      userId:
        type: "integer"
        format: "int64"
      authKey:
        type: "string"
      expiry:
        type: "string"
        format: "date-time"
    example:
      authKey: "authKey"
      expiry: "2000-01-23T04:56:07.000+00:00"
      userId: 0
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
